local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")
local AL = LibStub("AceLocale-3.0"):GetLocale("AtlasLoot")

local MAX_ARGUMENTS = 6

function AtlasLoot:CreateAdvancedSearchFrame()
    --Create Main Search Panel
    self.searchPanel = CreateFrame("FRAME", "AtlasLootDefaultFrame_AdvancedSearchPanel", self.mainUI.lootBackground, nil)
    self.searchPanel:SetPoint("TOPLEFT", self.mainUI.lootBackground, "TOPLEFT", 2, -2)
    self.searchPanel:SetSize(510, 510)
    self.searchPanel.closebtn = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_CloseButton", self.searchPanel, "UIPanelCloseButton")
    self.searchPanel.closebtn:SetPoint("TOPRIGHT", self.searchPanel, "TOPRIGHT", -10, -10)
    self.searchPanel:Hide()
    self.searchPanel.Label = self.searchPanel:CreateFontString(nil,"OVERLAY","GameFontHighlightLarge")
    self.searchPanel.Label:SetPoint("TOP", self.searchPanel, "TOP")
    self.searchPanel.Label:SetSize(512,30)
    self.searchPanel.Label:SetJustifyH("CENTER")
    self.searchPanel.Label:SetText("Advanced Search")
    self.searchPanel.closebtn:SetScript("OnClick", function() AtlasLoot:AdvancedSearchClose() end)
    self.searchPanel.closebtn:SetScript("OnShow", function(self) self:SetFrameLevel( (self:GetParent()):GetFrameLevel() + 1 ) end)

    --Create search/name box
    self.searchPanel.searchbox = CreateFrame("EditBox", "AtlasLootDefaultFrame_AdvancedSearchPanel_SearchBox", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.searchbox:SetSize(265, 35)
    self.searchPanel.searchbox:SetPoint("TOPLEFT", self.searchPanel, "TOPLEFT", 30, -55)
    self.searchPanel.searchbox:SetMaxLetters(100)
    self.searchPanel.searchbox:SetAutoFocus(false)
    self.searchPanel.searchbox:SetTextInsets(0, 8, 0, 0)
    self.searchPanel.searchbox.title = self.searchPanel.searchbox:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.searchbox.title:SetText("Name: ")
    self.searchPanel.searchbox.title:SetPoint("TOPLEFT", self.searchPanel.searchbox, "TOPLEFT", -3, 8)
    self.searchPanel.searchbox:SetScript("OnEnterPressed", function(editbox)
        self:AdvancedSearch(editbox:GetText())
        editbox:ClearFocus()
    end)
    self.searchPanel.searchbox:SetScript("OnShow", function(frame) frame:SetFrameLevel( (frame:GetParent()):GetFrameLevel() + 1 ) end)

    --Create quality button
    self.searchPanel.searchCategory = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_CategoryButton", self.searchPanel, "OptionsButtonTemplate")
    self.searchPanel.searchCategory:SetSize(130, 20)
    self.searchPanel.searchCategory:SetPoint("LEFT", self.searchPanel.searchbox, "RIGHT", 15, 0)
    self.searchPanel.searchCategory:SetText("Category Select")
    self.searchPanel.searchCategory:SetScript("OnClick", function(frame)
        local point1, _, point2 = self:GetTipAnchor(self.searchPanel.searchCategory)
        self:ShowSearchOptions(frame, {point1, point2})
    end)
    self.searchPanel.searchCategory:SetScript("OnShow", function(frame) frame:SetFrameLevel( (frame:GetParent()):GetFrameLevel() + 1 ) end)

    --Create equip type button
    self.searchPanel.equipbtn = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_EquipButton", self.searchPanel, "OptionsButtonTemplate")
    self.searchPanel.equipbtn:SetSize(130, 20)
    self.searchPanel.equipbtn:SetPoint("TOPLEFT", self.searchPanel.searchbox, "BOTTOMLEFT", -8, -25)
    self.searchPanel.equipbtn.title = self.searchPanel.equipbtn:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.equipbtn.title:SetText("Item Type: ")
    self.searchPanel.equipbtn.title:SetPoint("TOPLEFT", self.searchPanel.equipbtn, "TOPLEFT", 3, 15)

    --Create equip sub type button
    self.searchPanel.equipbtn.subbtn = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_EquipSubButton", self.searchPanel.equipbtn, "OptionsButtonTemplate")
    self.searchPanel.equipbtn.subbtn:SetSize(130, 20)
    self.searchPanel.equipbtn.subbtn:SetPoint("LEFT", self.searchPanel.equipbtn, "RIGHT", 15, 0)
    self.searchPanel.equipbtn.subbtn.title = self.searchPanel.equipbtn.subbtn:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.equipbtn.subbtn.title:SetText("Item Subtype: ")
    self.searchPanel.equipbtn.subbtn.title:SetPoint("TOPLEFT", self.searchPanel.equipbtn.subbtn, "TOPLEFT", 3, 15)
    self.searchPanel.equipbtn:SetScript("OnClick", function(button) self:DewdropToggle(button) end)
    self.searchPanel.equipbtn:SetScript("OnShow", function(button) button:SetFrameLevel( (button:GetParent()):GetFrameLevel() + 1 ) end)
    self.searchPanel.equipbtn.subbtn:SetScript("OnClick", function(button) self:DewdropToggle(button) end)
    self.searchPanel.equipbtn.subbtn:SetScript("OnShow", function(button) button:SetFrameLevel( (button:GetParent()):GetFrameLevel() + 1 ) end)

    self.searchPanel.levelmin = CreateFrame("EditBox", "AtlasLootDefaultFrame_AdvancedSearchPanel_LevelMin", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.levelmin:SetSize(47, 35)
    self.searchPanel.levelmin:SetPoint("TOPLEFT", self.searchPanel.searchbox, "BOTTOMLEFT", 0, -70)
    self.searchPanel.levelmin:SetMaxLetters(3)
    self.searchPanel.levelmin:SetAutoFocus(false)
    self.searchPanel.levelmin:SetTextInsets(0, 8, 0, 0)
    self.searchPanel.levelmin.title = self.searchPanel.levelmin:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.levelmin.title:SetText("Required Level: ")
    self.searchPanel.levelmin.title:SetPoint("TOPLEFT", self.searchPanel.levelmin, "TOPLEFT", -3, 8)

    self.searchPanel.levelmax = CreateFrame("EditBox", "AtlasLootDefaultFrame_AdvancedSearchPanel_LevelMax", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.levelmax:SetSize(47, 35)
    self.searchPanel.levelmax:SetPoint("LEFT", self.searchPanel.levelmin, "RIGHT", 25, 0)
    self.searchPanel.levelmax:SetMaxLetters(3)
    self.searchPanel.levelmax:SetAutoFocus(false)
    self.searchPanel.levelmax:SetTextInsets(0, 8, 0, 0)

    self.searchPanel.ilevelmin = CreateFrame("EditBox", "AtlasLootDefaultFrame_AdvancedSearchPanel_iLevelMin", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.ilevelmin:SetSize(47, 35)
    self.searchPanel.ilevelmin:SetPoint("LEFT", self.searchPanel.levelmax, "RIGHT", 25, 0)
    self.searchPanel.ilevelmin:SetMaxLetters(3)
    self.searchPanel.ilevelmin:SetAutoFocus(false)
    self.searchPanel.ilevelmin:SetTextInsets(0, 8, 0, 0)
    self.searchPanel.ilevelmin.title = self.searchPanel.ilevelmin:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.ilevelmin.title:SetText("Item Level: ")
    self.searchPanel.ilevelmin.title:SetPoint("TOPLEFT", self.searchPanel.ilevelmin, "TOPLEFT", -3, 8)

    self.searchPanel.ilevelmax = CreateFrame("EditBox", "AtlasLootDefaultFrame_AdvancedSearchPanel_iLevelMax", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.ilevelmax:SetSize(47, 35)
    self.searchPanel.ilevelmax:SetPoint("LEFT", self.searchPanel.ilevelmin, "RIGHT", 25, 0)
    self.searchPanel.ilevelmax:SetMaxLetters(3)
    self.searchPanel.ilevelmax:SetAutoFocus(false)
    self.searchPanel.ilevelmax:SetTextInsets(0, 8, 0, 0)

    self.searchPanel.useleveltick = CreateFrame("CheckButton", "AtlasLootDefaultFrame_AdvancedSearchPanel_LevelToggle", self.searchPanel, "ChatConfigCheckButtonTemplate")
    self.searchPanel.useleveltick:SetSize(20, 20)
    self.searchPanel.useleveltick:SetPoint("TOPRIGHT", self.searchPanel.levelmax, "BOTTOMRIGHT", 0, 5)
    self.searchPanel.useleveltick.title = self.searchPanel.useleveltick:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.useleveltick.title:SetText("Use Current Lv: ")
    self.searchPanel.useleveltick.title:SetPoint("TOPLEFT", self.searchPanel.levelmin, "BOTTOMLEFT", 0, 5)
    self.searchPanel.useleveltick:SetScript("OnClick", function(button)
        if(button:GetChecked()) then self.searchPanel.levelmax:Hide() self.searchPanel.levelmin:Hide()
        else self.searchPanel.levelmax:Show() self.searchPanel.levelmin:Show()
        end
    end)

    self.searchPanel.argpanel = CreateFrame("Frame", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainer", self.searchPanel)
    self.searchPanel.argpanel:SetSize(450, 340)
    self.searchPanel.argpanel:SetPoint("TOPLEFT", self.searchPanel.levelmin, "BOTTOMLEFT", 0, -40)
    self.searchPanel.argpanel.title = self.searchPanel.argpanel:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.argpanel.title:SetText("Additional Filters: ")
    self.searchPanel.argpanel.title:SetPoint("TOPLEFT", self.searchPanel.argpanel, "TOPLEFT", 0, 0)

    self.searchPanel.addArg = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainerAddArgBtn", self.searchPanel.argpanel, "OptionsButtonTemplate")
    self.searchPanel.addArg:SetPoint("TOP", self.searchPanel.useleveltick, "BOTTOM", 5, -20)
    self.searchPanel.addArg:SetSize(20, 20)
    self.searchPanel.addArg:SetText("+")
    self.searchPanel.addArg:SetScript("OnClick", function(button)
        self:AddArgumentContainer()
    end)

    self.searchPanel.remArg = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainerRemArgBtn", self.searchPanel.argpanel, "OptionsButtonTemplate")
    self.searchPanel.remArg:SetPoint("LEFT", self.searchPanel.addArg, "RIGHT", 10, 0)
    self.searchPanel.remArg:SetSize(20, 20)
    self.searchPanel.remArg:SetText("-")
    self.searchPanel.remArg:SetScript("OnClick", function(button)
        self:RemoveArgumentContainer()
    end)
    self.searchPanel.remArg:Disable()
    self.searchPanel.main = {}
    self.searchPanel.sub = {}
    self.searchPanel.value = {}
    for i = 1, MAX_ARGUMENTS do
        self.searchPanel.main[i] = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainer" .. i, self.searchPanel.argpanel, "OptionsButtonTemplate")
        self.searchPanel.main[i]:SetPoint("TOPLEFT", self.searchPanel.argpanel, "TOPLEFT", 0, -((i - 1) * 35)-20)
        self.searchPanel.main[i]:SetSize(130, 20)
        self.searchPanel.main[i]:SetScript("OnClick", function(button)  self:DewdropToggle(button) end)
        self.searchPanel.main[i]:Hide()
        self.searchPanel.main[i]:SetText("Select Option")

        self.searchPanel.sub[i] = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainer" .. i .. "Sub", self.searchPanel.argpanel, "OptionsButtonTemplate")
        self.searchPanel.sub[i]:SetPoint("LEFT", self.searchPanel.main[i], "RIGHT", 15, 0)
        self.searchPanel.sub[i]:SetSize(130, 20)
        self.searchPanel.sub[i]:SetScript("OnClick", function(button) self:DewdropToggle(button) end)
        self.searchPanel.sub[i]:Hide()
        self.searchPanel.sub[i]:SetText("Select Option")
        self.searchPanel.sub[i]:Disable()

        self.searchPanel.value[i] = CreateFrame("EditBox", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainer" .. i .. "Value", self.searchPanel.argpanel, "InputBoxTemplate")
        self.searchPanel.value[i]:SetPoint("LEFT", self.searchPanel.sub[i], "RIGHT", 15, 0)
        self.searchPanel.value[i]:SetSize(65, 35)
        self.searchPanel.value[i]:SetAutoFocus(false)
        self.searchPanel.value[i]:SetTextInsets(0, 8, 0, 0)
        self.searchPanel.value[i]:SetScript("OnEnterPressed", function(frame)
            frame:ClearFocus()
        end)
        self.searchPanel.value[i]:Hide()
    end

    --Search Button
    self.searchPanel.searchbtn = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_SearchButton", self.searchPanel, "UIPanelButtonTemplate2")
    self.searchPanel.searchbtn:SetSize(70,32)
    self.searchPanel.searchbtn:SetPoint("BOTTOMLEFT", self.searchPanel, "BOTTOMLEFT", 20, 20)

    self.searchPanel.searchbtn:SetScript("OnShow", function(self)
        self:SetText(AL["Search"])
        self:SetFrameLevel( (self:GetParent()):GetFrameLevel() + 1 )
    end)
    self.searchPanel.searchbtn:SetScript("OnClick", function()
        AtlasLoot:AdvancedSearch(self.searchPanel.searchbox:GetText())
        self.searchPanel.searchbox:ClearFocus()
    end)

    self.searchPanel.clearbtn = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_ClearButton", self.searchPanel, "UIPanelButtonTemplate2")
    self.searchPanel.clearbtn:SetSize(70,32)
    self.searchPanel.clearbtn:SetPoint("LEFT", self.searchPanel.searchbtn, "RIGHT", 20, 0)
    self.searchPanel.clearbtn:SetScript("OnShow", function(button)
        button:SetText(AL["Clear"])
        button:SetFrameLevel( (button:GetParent()):GetFrameLevel() + 1 )
    end)
    self.searchPanel.clearbtn:SetScript("OnClick", function()
        self:AdvancedSearchReset()
        self.searchPanel.searchbox:SetText("")
        self.searchPanel.searchbox:ClearFocus()
    end)

    self:InitializeAdvancedSearch()
    self:AdvancedSearchSetup()
end