local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")
local AL = LibStub("AceLocale-3.0"):GetLocale("AtlasLoot")

local MAX_ARGUMENTS = 6

local framename = "AtlasLootDefaultFrame_AdvancedSearchPanel"
function AtlasLoot:CreateAdvancedSearchFrame()
    --Create Main Search Panel
    self.searchPanel = CreateFrame("FRAME", framename, self.mainUI.lootBackground, nil)
    self.searchPanel:SetPoint("TOPLEFT", self.mainUI.lootBackground, "TOPLEFT", 2, -2)
    self.searchPanel:SetSize(510, 510)
    self.searchPanel.closebtn = CreateFrame("Button", framename.."_CloseButton", self.searchPanel, "UIPanelCloseButton")
    self.searchPanel.closebtn:SetPoint("TOPRIGHT", self.searchPanel, "TOPRIGHT", -10, -10)
    self.searchPanel:Hide()
    self.searchPanel.closebtn:SetScript("OnClick", function() AtlasLoot:AdvancedSearchClose() end)
    self.searchPanel.closebtn:SetScript("OnShow", function(self) self:SetFrameLevel( (self:GetParent()):GetFrameLevel() + 1 ) end)

    --Create search/name box
    self.searchPanel.searchbox = CreateFrame("EditBox", framename.."_SearchBox", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.searchbox:SetSize(265, 35)
    self.searchPanel.searchbox:SetPoint("TOPLEFT", self.searchPanel, "TOPLEFT", 30, -55)
    self.searchPanel.searchbox:SetMaxLetters(100)
    self.searchPanel.searchbox:SetAutoFocus(false)
    self.searchPanel.searchbox:SetTextInsets(0, 8, 0, 0)
    self.searchPanel.searchbox.title = self.searchPanel.searchbox:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.searchbox.title:SetText("Name: ")
    self.searchPanel.searchbox.title:SetPoint("TOPLEFT", self.searchPanel.searchbox, "TOPLEFT", -3, 8)
    self.searchPanel.searchbox:SetScript("OnEnterPressed", function(editbox)
        self:AdvancedSearch(editbox:GetText())
        editbox:ClearFocus()
    end)
    self.searchPanel.searchbox:SetScript("OnShow", function(frame) frame:SetFrameLevel( (frame:GetParent()):GetFrameLevel() + 1 ) end)

    --Create quality button
    self.searchPanel.searchCategory = CreateFrame("Button", framename.."_CategoryButton", self.searchPanel, "OptionsButtonTemplate")
    self.searchPanel.searchCategory:SetSize(130, 20)
    self.searchPanel.searchCategory:SetPoint("LEFT", self.searchPanel.searchbox, "RIGHT", 15, 0)
    self.searchPanel.searchCategory:SetText("Category Select")
    self.searchPanel.searchCategory:SetScript("OnClick", function(frame)
        local point1, _, point2 = self:GetTipAnchor(self.searchPanel.searchCategory)
        self:ShowSearchOptions(frame, {point1, point2})
    end)
    self.searchPanel.searchCategory:SetScript("OnShow", function(frame) frame:SetFrameLevel( (frame:GetParent()):GetFrameLevel() + 1 ) end)

    --Create equip type button
    self.searchPanel.equipbtn = CreateFrame("Button", framename.."_EquipButton", self.searchPanel, "OptionsButtonTemplate")
    self.searchPanel.equipbtn:SetSize(130, 20)
    self.searchPanel.equipbtn:SetPoint("TOPLEFT", self.searchPanel.searchbox, "BOTTOMLEFT", -8, -25)
    self.searchPanel.equipbtn.title = self.searchPanel.equipbtn:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.equipbtn.title:SetText("Item Type: ")
    self.searchPanel.equipbtn.title:SetPoint("TOPLEFT", self.searchPanel.equipbtn, "TOPLEFT", 3, 15)

    --Create equip sub type button
    self.searchPanel.equipbtn.subbtn = CreateFrame("Button", framename.."_EquipSubButton", self.searchPanel.equipbtn, "OptionsButtonTemplate")
    self.searchPanel.equipbtn.subbtn:SetSize(130, 20)
    self.searchPanel.equipbtn.subbtn:SetPoint("LEFT", self.searchPanel.equipbtn, "RIGHT", 15, 0)
    self.searchPanel.equipbtn.subbtn.title = self.searchPanel.equipbtn.subbtn:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.equipbtn.subbtn.title:SetText("Item Subtype: ")
    self.searchPanel.equipbtn.subbtn.title:SetPoint("TOPLEFT", self.searchPanel.equipbtn.subbtn, "TOPLEFT", 3, 15)
    self.searchPanel.equipbtn:SetScript("OnClick", function(button) self:DewdropToggle(button) end)
    self.searchPanel.equipbtn:SetScript("OnShow", function(button) button:SetFrameLevel( (button:GetParent()):GetFrameLevel() + 1 ) end)
    self.searchPanel.equipbtn.subbtn:SetScript("OnClick", function(button) self:DewdropToggle(button) end)
    self.searchPanel.equipbtn.subbtn:SetScript("OnShow", function(button) button:SetFrameLevel( (button:GetParent()):GetFrameLevel() + 1 ) end)

    self.searchPanel.levelminbox = CreateFrame("EditBox", framename.."_LevelMin", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.levelminbox:SetSize(47, 35)
    self.searchPanel.levelminbox:SetPoint("TOPLEFT", self.searchPanel.searchbox, "BOTTOMLEFT", 0, -70)
    self.searchPanel.levelminbox:SetMaxLetters(3)
    self.searchPanel.levelminbox:SetAutoFocus(false)
    self.searchPanel.levelminbox:SetTextInsets(0, 8, 0, 0)
    self.searchPanel.levelminbox.title = self.searchPanel.levelminbox:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.levelminbox.title:SetText("Required Level: ")
    self.searchPanel.levelminbox.title:SetPoint("TOPLEFT", self.searchPanel.levelminbox, "TOPLEFT", -3, 8)

    self.searchPanel.levelmaxbox = CreateFrame("EditBox", framename.."_LevelMax", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.levelmaxbox:SetSize(47, 35)
    self.searchPanel.levelmaxbox:SetPoint("LEFT", self.searchPanel.levelminbox, "RIGHT", 25, 0)
    self.searchPanel.levelmaxbox:SetMaxLetters(3)
    self.searchPanel.levelmaxbox:SetAutoFocus(false)
    self.searchPanel.levelmaxbox:SetTextInsets(0, 8, 0, 0)

    self.searchPanel.ilevelminbox = CreateFrame("EditBox", framename.."_iLevelMin", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.ilevelminbox:SetSize(47, 35)
    self.searchPanel.ilevelminbox:SetPoint("LEFT", self.searchPanel.levelmaxbox, "RIGHT", 25, 0)
    self.searchPanel.ilevelminbox:SetMaxLetters(3)
    self.searchPanel.ilevelminbox:SetAutoFocus(false)
    self.searchPanel.ilevelminbox:SetTextInsets(0, 8, 0, 0)
    self.searchPanel.ilevelminbox.title = self.searchPanel.ilevelminbox:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.ilevelminbox.title:SetText("Item Level: ")
    self.searchPanel.ilevelminbox.title:SetPoint("TOPLEFT", self.searchPanel.ilevelminbox, "TOPLEFT", -3, 8)

    self.searchPanel.ilevelmaxbox = CreateFrame("EditBox", framename.."_iLevelMax", self.searchPanel, "InputBoxTemplate")
    self.searchPanel.ilevelmaxbox:SetSize(47, 35)
    self.searchPanel.ilevelmaxbox:SetPoint("LEFT", self.searchPanel.ilevelminbox, "RIGHT", 25, 0)
    self.searchPanel.ilevelmaxbox:SetMaxLetters(3)
    self.searchPanel.ilevelmaxbox:SetAutoFocus(false)
    self.searchPanel.ilevelmaxbox:SetTextInsets(0, 8, 0, 0)

    self.searchPanel.useleveltick = CreateFrame("CheckButton", framename.."_LevelToggle", self.searchPanel, "ChatConfigCheckButtonTemplate")
    self.searchPanel.useleveltick:SetSize(20, 20)
    self.searchPanel.useleveltick:SetPoint("TOPRIGHT", self.searchPanel.levelmaxbox, "BOTTOMRIGHT", 0, 5)
    self.searchPanel.useleveltick.title = self.searchPanel.useleveltick:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.useleveltick.title:SetText("Use Current Lv: ")
    self.searchPanel.useleveltick.title:SetPoint("TOPLEFT", self.searchPanel.levelminbox, "BOTTOMLEFT", 0, 5)
    self.searchPanel.useleveltick:SetScript("OnClick", function(self, button)
        if(self:GetChecked()) then self.searchPanel.levelmaxbox:Hide() self.searchPanel.levelminbox:Hide() 
        else self.searchPanel.levelmaxbox:Show() self.searchPanel.levelminbox:Show()
        end
    end)

    self.searchPanel.argpanel = CreateFrame("Frame", framename.."_ArgumentContainer", self.searchPanel)
    self.searchPanel.argpanel:SetSize(450, 340)
    self.searchPanel.argpanel:SetPoint("TOPLEFT", self.searchPanel.levelminbox, "BOTTOMLEFT", 0, -40)
    self.searchPanel.argpanel.title = self.searchPanel.argpanel:CreateFontString(nil, "ARTWORK", "GameFontNormal")
    self.searchPanel.argpanel.title:SetText("Additional Filters: ")
    self.searchPanel.argpanel.title:SetPoint("TOPLEFT", self.searchPanel.argpanel, "TOPLEFT", 0, 0)

    self.searchPanel.addArg = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainerAddArgBtn", self.searchPanel.argpanel, "OptionsButtonTemplate")
    self.searchPanel.addArg:SetPoint("TOP", self.searchPanel.useleveltick, "BOTTOM", 5, -20)
    self.searchPanel.addArg:SetSize(20, 20)
    self.searchPanel.addArg:SetText("+")
    self.searchPanel.addArg:SetScript("OnClick", function(self, button)
        AtlasLoot:AddArgumentContainer()
    end)

    self.searchPanel.remArg = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainerRemArgBtn", self.searchPanel.argpanel, "OptionsButtonTemplate")
    self.searchPanel.remArg:SetPoint("LEFT", self.searchPanel.addArg, "RIGHT", 10, 0)
    self.searchPanel.remArg:SetSize(20, 20)
    self.searchPanel.remArg:SetText("-")
    self.searchPanel.remArg:SetScript("OnClick", function(self, button)
        AtlasLoot:RemoveArgumentContainer()
    end)
    self.searchPanel.remArg:Disable()

    for n = 1, MAX_ARGUMENTS do
        local btn = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainer" .. tostring(n), self.searchPanel.argpanel, "OptionsButtonTemplate")
        btn:SetPoint("TOPLEFT", self.searchPanel.argpanel, "TOPLEFT", 0, -((n - 1) * 35)-20)
        btn:SetSize(130, 20)
        btn:SetScript("OnClick", function(button)
            if self.SearchMenus.ArgumentMenus[n]:IsOpen() then
                self.SearchMenus.ArgumentMenus[n]:Close()
            else
                self.SearchMenus.ArgumentMenus[n]:Open(button)
            end
        end)
        btn:Hide()
        btn:SetText("Select Option")

        local sub = CreateFrame("Button", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainer" .. tostring(n) .. "Sub", self.searchPanel.argpanel, "OptionsButtonTemplate")
        sub:SetPoint("LEFT", btn, "RIGHT", 15, 0)
        sub:SetSize(130, 20)
        sub:SetScript("OnClick", function(button)
            if self.SearchMenus.ArgumentSubMenus[n]:IsOpen() then
                self.SearchMenus.ArgumentSubMenus[n]:Close()
            else
                self.SearchMenus.ArgumentSubMenus[n]:Open(button)
            end
        end)
        sub:Hide()
        sub:Disable()

        local txt = CreateFrame("EditBox", "AtlasLootDefaultFrame_AdvancedSearchPanel_ArgumentContainer" .. tostring(n) .. "Value", self.searchPanel.argpanel, "InputBoxTemplate")
        txt:SetPoint("LEFT", sub, "RIGHT", 15, 0)
        txt:SetSize(65, 35)
        txt:SetAutoFocus(false)
        txt:SetTextInsets(0, 8, 0, 0)
        txt:SetScript("OnEnterPressed", function(self)
            self:ClearFocus()
        end)
        txt:Hide()
    end

    --Search Button
    self.searchPanel.searchbtn = CreateFrame("Button", framename.."_SearchButton", self.searchPanel, "UIPanelButtonTemplate2")
    self.searchPanel.searchbtn:SetSize(70,32)
    self.searchPanel.searchbtn:SetPoint("BOTTOMLEFT", self.searchPanel, "BOTTOMLEFT", 20, 20)

    self.searchPanel.searchbtn:SetScript("OnShow", function(self)
        self:SetText(AL["Search"])
        self:SetFrameLevel( (self:GetParent()):GetFrameLevel() + 1 )
    end)
    self.searchPanel.searchbtn:SetScript("OnClick", function()
        AtlasLoot:AdvancedSearch(self.searchPanel.searchbox:GetText())
        self.searchPanel.searchbox:ClearFocus()
    end)

    self.searchPanel.clearbtn = CreateFrame("Button", framename.."_ClearButton", self.searchPanel, "UIPanelButtonTemplate2")
    self.searchPanel.clearbtn:SetSize(70,32)
    self.searchPanel.clearbtn:SetPoint("LEFT", self.searchPanel.searchbtn, "RIGHT", 20, 0)
    self.searchPanel.clearbtn:SetScript("OnShow", function(button)
        button:SetText(AL["Clear"])
        button:SetFrameLevel( (button:GetParent()):GetFrameLevel() + 1 )
    end)
    self.searchPanel.clearbtn:SetScript("OnClick", function()
        self:AdvancedSearchReset()
        self.searchPanel.searchbox:SetText("")
        self.searchPanel.searchbox:ClearFocus()
    end)
end