name: Release WoW Addon

on:
  push:
    tags:
      - "*.*.*" # Trigger on tags like v1.2.3

env:
  ADDON_NAME: AtlasLoot   # 👈 change this for each addon repo (folder + toc base name)
  ZIP_FILE_NAME: AtlasLootAscension

jobs:
  release:
    name: Create Release if New Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get latest tag with git
        id: get_tag
        run:  |
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Prepare release zip
        run: |
          version="${{ steps.get_tag.outputs.tag }}"
          echo "VERSION=$version" >> $GITHUB_ENV
          zip_name="${env.ZIP_FILE_NAME}-v${env.VERSION}.zip"
          echo "Preparing zip for $ADDON_NAME -> $zip_name"
          
          # Copy only the addon folder and exclude metadata
          rsync -av --exclude='.git' --exclude='.github' --exclude='*.zip' AtlasLoot AtlasLoot_Cache AtlasLoot_BurningCrusade AtlasLoot_Crafting_OriginalWoW AtlasLoot_Crafting_TBC AtlasLoot_Crafting_Wrath AtlasLoot_OriginalWoW AtlasLoot_Vanity AtlasLoot_WorldEvents AtlasLoot_WrathoftheLichKing "./temp_build/"
          
          cd ./temp_build
          zip -r "../${zip_name}" "${ADDON_NAME}"
          cd ..
          
          echo "ZIP_NAME=${zip_name}" >> $GITHUB_ENV
          echo "✅ Created ${zip_name}"
      - name: Create GitHub Release and Upload Zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: ${{ env.ADDON_NAME }} ${{ env.VERSION }}
          files: |
            ${{ env.ZIP_NAME }}

