name: Release WoW Addon

on:
  push:
    tags:
      - "*.*.*" # Trigger on tags like v1.2.3

env:
  ADDON_NAME: AtlasLoot   # 👈 change this for each addon repo (folder + toc base name)
  ZIP_FILE_NAME: AtlasLootAscension
  VERSION: ${github.ref_name}

jobs:
  release:
    name: Create Release if New Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare release zip
        run: |
          zip_name="${ZIP_FILE_NAME}-${VERSION}.zip"
          echo "Preparing zip for $ZIP_FILE_NAME -> $zip_name"
          
          # Copy only the addon folder and exclude metadata
          rsync -av --exclude='.git' --exclude='.github' --exclude='*.zip' "${ADDON_NAME}" "./temp_build/"
          
          cd ./temp_build
          zip -r "../${zip_name}" "${ZIP_FILE_NAME}"
          cd ..
          
          echo "ZIP_NAME=${zip_name}" >> $GITHUB_ENV
          echo "✅ Created ${zip_name}"
      - name: Create GitHub Release and Upload Zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: ${{ env.ADDON_NAME }} ${{ env.VERSION }}
          files: |
            ${{ env.ZIP_NAME }}

